# Generated by Django 3.2.2 on 2021-05-06 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_remove_video_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='videos.videolocation'),
            preserve_default=False,
        ),
    ]
