# Generated by Django 3.2 on 2021-04-25 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('square_meter', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('is_negotiabale', models.BooleanField(default=False)),
                ('main_picture', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('main_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('main_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('main_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('main_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('main_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('master_bedroom', models.IntegerField(default=0)),
                ('bathroom', models.IntegerField(default=0)),
                ('kitchen', models.IntegerField(default=0)),
                ('guest_toilet', models.BooleanField(default=True)),
                ('corridor', models.BooleanField(default=True)),
                ('store', models.BooleanField(default=True)),
                ('parking_garage', models.BooleanField(default=True)),
                ('elevator', models.BooleanField(default=True)),
                ('cctv', models.BooleanField(default=True)),
                ('garbage_shooter', models.BooleanField(default=True)),
                ('generator', models.BooleanField(default=True)),
                ('wifi', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
